data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  output_dir: "data/outputs"
  prompt_dir: "config/prompts"
  ground_truth_dir: "data/ground_truth/"

preprocessing:
  schema_file: "preprocessing/schema.json"


models:
  primary_llm:
    name: "mistralai/Mistral-7B-Instruct-v0.3"
    path: "models/primary_llm/"
    quantization: "4bit"
    max_tokens: 1024
    temperature: 0.3
    top_p: 0.85
    repetition_penalty: 1.15
    
  secondary_llm:
    name: "facebook/bart-large-cnn"
    path: "models/secondary_llm/"
    quantization: "4bit"
    max_tokens: 512
    temperature: 0.2

hardware:
  device: "cuda"
  max_memory: "8GB"

evaluation:
  output_dir: data/evaluation_results
  metrics:
    - bleu
    - rouge
    - bertscore
    - meteor
    - semantic