# config.yaml
data:
  raw_dir: "data/raw/"
  processed_dir: "data/processed/"
  ground_truth_dir: "data/ground_truth/"
  output_dir: "data/outputs/"
  prompt_dir: "config/prompts/"

models:
  primary_llm:
    name: "mistralai/Mixtral-8x7B-Instruct-v0.1"
    path: "models/primary_llm/"
    quantization: "4bit"
    max_tokens: 1024
  secondary_llm:
    name: "t5-small"
    path: "models/secondary_llm/"
    quantization: "8bit"
    max_tokens: 512

preprocessing:
  schema_file: "src/preprocessing/schema.json"
  output_format: "text"

evaluation:
  metrics:
    - "bleu"
    - "rouge"
    - "bertscore"
  output_dir: "data/outputs/evaluation/"

hardware:
  device: "cuda"
  max_memory: "8GB"